apiVersion: v1
kind: Service
metadata:
  labels:
    environment: development
    name: postgres-deployment
  name: postgres-deployment
  namespace: k8s-django-app-development
spec:
  ports:
  - nodePort: 30182
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    environment: development
    name: postgres-deployment
    tier: database
  type: NodePort
