apiVersion: v1
items:
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    creationTimestamp: 2018-01-11T07:26:26Z
    name: api-deployment
    namespace: k8s-django-app-development
  spec:
    maxReplicas: 8
    minReplicas: 3
    scaleTargetRef:
      apiVersion: extensions/v1beta1
      kind: Deployment
      name: api-deployment
    targetCPUUtilizationPercentage: 70
  status:
    currentReplicas: 2
    desiredReplicas: 2
    lastScaleTime: 2018-01-11T07:26:56Z
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
