apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: k8s-django-app-development
  name: postgres-data
  labels:
    name: postgres-data
    type: local
spec:
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  hostPath:
    path: /data/postgres
