apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: k8s-django-app-development
  name: postgres-data-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M
