apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: k8s-django-app-development
  name: postgres-deployment
  labels:
    name: postgres-deployment
    environment: development
spec:
  replicas: 1
  template:
    metadata:
      name: postgres-deployment
      labels:
        name: postgres-deployment
        tier: database
        environment: development
    spec:
      containers:
      - name: postgres-deployment
        image: postgres
        env:
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: db-user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: db-password
        resources:
          requests:
            memory: "64Mi"
            cpu: "125m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
        ports:
          - containerPort: 5432
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-claim
