apiVersion: batch/v1
kind: Job
metadata:
  name: api-database-setup
  namespace: k8s-django-app-development
spec:
  template:
    metadata:
      namespace: k8s-django-app-development
      name: api-database-setup
    spec:
      restartPolicy: Never
      containers:
      - name: api-database-setup
        image: postgres
        env:
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: db-user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-secrets
                key: db-password
        volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
        ports:
          - containerPort: 8000
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data-claim
